module.exports.authService = require('./auth.service');
module.exports.emailService = require('./email.service');
module.exports.newsService = require('./news.service');
module.exports.themeService = require('./theme.service');
module.exports.tokenService = require('./token.service');
module.exports.userService = require('./user.service');
module.exports.userProfileService = require('./userProfile.service');
module.exports.userRoleService = require('./userRole.service');
module.exports.coachProfileService=require('./coachProfile.service')
module.exports.studentService=require('./student.service')
module.exports.classificationService=require('./classification.service')
module.exports.classBaseService=require('./classBase.service')
module.exports.classZoneService=require('./classZone.service')
module.exports.classInstanceService=require('./classInstance.service')
module.exports.classScheduleService=require('./classSchedule.service')
module.exports.bookingService=require('./booking.service')
module.exports.classGroupService=require('./classGroup.service')
module.exports.classActivityService=require('./classActivity.service')
module.exports.orderService=require('./order.service')
module.exports.productService=require('./product.service')
module.exports.classEnrollmentService=require('./classEnrollment.service')
